### ISSUE TITLE
Design of page

### ISSUE THREAD

**Issue by linusromland** [svantejonssonITHS/Software-Life-Cycle-Management-Laboration-2#8]

**Comment by svante-jonsson** [comment]
Page design:
![image](https://user-images.githubusercontent.com/77492340/198992282-f49a97b3-a924-44db-ad5f-95fb6b516af3.png)

Also, [link to figma](https://www.figma.com/file/SZ7i7QP6IfYqHNDFstj3Nx/Software-Life-Cycle-Management-Laboration-2?node-id=0%3A1)
